### ISSUE TITLE
Clippy emits error in `1.0.22` but OK in `1.0.21` (small breaking change in a `patch` release)

### ISSUE THREAD

**Issue by nik-rev** [dtolnay/rustversion#65]
Hi, the following compiles OK in `=1.0.21` but updating to `=1.0.22` causes an error:

```rust
#![forbid(clippy::incompatible_msrv)]

trait M {}

#[rustversion::attr(since(1.78), diagnostic::do_not_recommend)]
impl M for () {}
```

```
$ cargo clippy

error[E0453]: allow(clippy::incompatible_msrv) incompatible with previous forbid
 --> src/main.rs:6:1
  |
1 | #![forbid(clippy::incompatible_msrv)]
  |           ------------------------- `forbid` level set here
...
6 | #[rustversion::attr(since(1.78), diagnostic::do_not_recommend)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ overruled by previous forbid
  |
  = note: this error originates in the attribute macro `rustversion::attr` (in Nightly builds, run with -Z macro-backtrace for more info)
```

`Cargo.toml`:

```rs
[package]
name = "x"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
rustversion = "=1.0.22"
```

---

`#[allow(clippy::incompatible_msrv)]` was added, this breaks code that is in a `forbid` context. This wouldn't be breaking if the `allow` was there only for cases that *already* emitted errors
